name: 🚀 Run

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 🚀 Run
        shell: bash
        run: |
          python main.py
